# ======= WSL2 Default Nameservers ==============
# cat /etc/resolv.conf                                                
# This file was automatically generated by WSL. To stop automatic generation of this file, add the following entry to /etc/wsl.conf:
# [network]
# generateResolvConf = false
# nameserver 172.31.64.1

echo "nameserver 8.8.8.8" > /etc/resolv.conf
echo "nameserver 8.8.4.4" >> /etc/resolv.conf

if [[ -n $1 && $1 == "-c" ]]; then
    echo "ping output available! use -p"
    cat /etc/resolv.conf
elif [[ -n $1 && $1 == "-p" ]]; then
    echo "cat output available! use -c"
    ping -c 3 google.com
else 
    echo "cat and ping output available! use -p or -c"
fi